### ISSUE TITLE
Update how to light a ELIXIR Beacon documentation

### ISSUE THREAD

**Issue by juhtornr** [ga4gh-beacon/specification#129]

**Comment by juhtornr** [comment]
Issue moved to [ga4gh-beacon/ga4gh-beacon.github.io #20](https://github.com/ga4gh-beacon/ga4gh-beacon.github.io/issues/20) via [**ZenHub**](https://www.zenhub.com/)

**Comment by teemukataja** [comment]
Issues with Quick Start -guide:

##### Firstly
`createuser -P microaccounts_dev` should be `createuser -P microaccounts_dev -U postgres` like with the `createdb`-commands above, otherwise an error is returned that a connection to database could not be made.

##### Secondly
The insert-command doesn't go through, even though the view is created from elixir_beacon_db_schema.sql. It seems that a rule is required first, because the insertion targets a view and not a table.
```
elixir_beacon_dev=> INSERT INTO beacon_dataset(id, description, access_type, reference_genome, size) VALUES ('EGAD00000000028', 'Sample variants', 'PUBLIC', 'grch37', 34114);
ERROR:  cannot insert into view "beacon_dataset"
HINT:  You need an unconditional ON INSERT DO INSTEAD rule or an INSTEAD OF INSERT trigger.
```
