### ISSUE TITLE
Should alternateBases be required?

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification#169]
Definition of `alternateBases` says accepted values are `[ACGT]*` or `N` (see [here](https://github.com/ga4gh-beacon/specification/blob/fe733650eba2ae831d6afacb49d1c81c1b8711db/beacon.yaml#L127)). Should we make this field required? I assume `N` should be used when `variantType`is provided, but if it's not required I don't see the point of having this value (you can simply leave this field empty).
WDYT?

**Comment by mbaudis** [comment]
Logically, `N` does not make sense when querying a non-precise variant (e.g. `DEL` ...), since `N` stands for "sequence of unknown composition and length 1" (my interpretation). The same way is true for `referenceBases`, if doing a range match.

I think query validation should not be on single elements, but on semantically correct queries.

Some earlier version of the proposal for structural variants did not require `...Bases`, and our backend doesn't check in case `variantType` exists.

Both options work, if documented properly... but I would be for optional.
