### ISSUE TITLE
Allow wildcards

### ISSUE THREAD

**Issue by mfiume** [ga4gh-beacon/specification#21]
Proposal by Michael Baudis, please elaborate if insufficient.

Accept both “referenceBases” and/or “alternateBases” parameters to be empty.
E.g. not specifying any of them would return true if at least one variant is found in that position of the chromosome. This is also logical when querying against “imprecise” variants
Definition of mapping of imprecise events (i.e. with CIPOS, CIEND values)
Definition if/how partial overlaps in range queries are handled (e.g. a large deletion overlapping some of a gene’s CDR)

**Comment by jrambla** [comment]
+0
I'm guessing we need more feedback from Michael.

**Comment by sdelatorrep** [comment]
I think we're already covering the first case (empty referenceBases): see [protobuf definition](https://github.com/ga4gh-beacon/specification/blob/23165dfb878da2be48e31fc890971bbe76dc443f/src/main/proto/ga4gh/beacon.proto#L52).
BTW, we're missing this field's description in the OpenAPI definition (see [this](https://github.com/ga4gh-beacon/specification/blob/03a28806a78bd0dbc296e85ae8fde0e5124529ca/beacon.yaml#L131)).

**Comment by sdelatorrep** [comment]
And I believe that the second case is also covered because `alternateBases` is optional if `variantType` is provided (see [this](https://github.com/ga4gh-beacon/specification/blob/23165dfb878da2be48e31fc890971bbe76dc443f/src/main/proto/ga4gh/beacon.proto#L66)). WDYT?

**Comment by mbaudis** [comment]
Covered in 0.4 (after final fixes); see last comments by @sdelatorrep.

**Comment by sdelatorrep** [comment]
Hi @mbaudis, I've got a question about this. Here we said that the beacon should accept both`referenceBases` and `alternateBases` to be empty but in the current specification the first field is mandatory. Is `referenceBases=N` the expected value to be used as a wildcard?

**Comment by mbaudis** [comment]
Yes, as far as i remember this was the compromise (i.e. there is a ref base but it is not known). I was for leaving it optional (if no alt, no ref), but this is/was a conceptual decision.

**Comment by antbro** [comment]
IMO... ref should be optional. The position is defined by other fields and so only the allele being sought needs to be specified. I personally do not think that allele is ‘alt’ but just “allele”. Otherwise how does one query for a base that happens to be the red allele?
But given the options at hand the alt place is the best place to state the allele being sought.
When ref is provided it offers a (imperfect) way to sanity check the position info - but who really does that? Great if we all did though, given ambiguity over build, patch, 0/1/inter base assumptions
Cheers
Tony

Sent from my iPhone

On 5 Oct 2018, at 13:46, Michael Baudis <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, as far as i remember this was the compromise (i.e. there is a ref base but it is not known). I was for leaving it optional (if no alt, no ref), but this is/was a conceptual decision.
