### ISSUE TITLE
Add support for HTTP Authorisation header to Beacon (query) API

### ISSUE THREAD

**Issue by mfiume** [ga4gh-beacon/specification#24]

**Comment by sdelatorrep** [comment]
Please, consider this proposal:
- accessType: public/registered/controlled
- accessInformation: link to the access information/conditions

E.g. In the EGA context:
- for controlled datasets, a link to the dataset webpage
- for registered datasets, a link to a page explaining that all EGA users are registered.

**Comment by antbro** [comment]
Is the term "registered" likely to mean the same thing in all contexts?
Some might take it to mean someone has registered into a list/site, 
others might take it to mean they are a registered (genuine) researcher
Cheers
Tony


sdelatorrep wrote:

**Comment by sdelatorrep** [comment]
Hi @antbro, the "registered" concept is described [here](https://genomicsandhealth.org/working-groups/our-work/registered-access) (the attestation step does not exist yet in the EGA and I didn't include it in my example).

**Comment by juhtornr** [comment]
Registed access is implemented in ELIXIR Beacon reference implementation in https://github.com/ga4gh-beacon/beacon-elixir/pull/2 

It works so that when you provide OAuth2 access token in HTTP Authorisation header you will gain access to registered access datasets. However this wasn't brought to the API and therefore I'll change the title of this issue.

**Comment by jrambla** [comment]
We consider this feature done by other means. Closing it.
