### ISSUE TITLE
Relationship between HATEOAS and handover ?

### ISSUE THREAD

**Issue by blankdots** [ga4gh-beacon/specification#276]
Because there seems to be no reply to: https://github.com/ga4gh-beacon/specification/pull/230#issuecomment-476081737 I will create a new issue and we can discuss it here.

This is a question for @sdelatorrep and @mbaudis, how does `handover` relate to HATEOAS and HAL it seems there is a connection or at least I think `handover` could benefit and borrow some of the concepts from those RESTful style and model.
I did read through #114 and PR #230 and it seems that this `handover` provides links to additional resources of a certain type (or ontology - here I think there could have been other w3c specifications used for inspiration but i am limiting the scope of this issue) or did I misunderstand the purpose of the handover mechanism ?

**Comment by sdelatorrep** [comment]
@jrambla?

**Comment by mbaudis** [comment]
@blankdots That depends if/when we define handover protocol types or examples. So far, _handover_ is a vehicle to allow the delivery of data _beyond and outside_ of the Beacon specifications, but initiated by and derived from a Beacon query. Basically a URL and something about what this willl lead to.
IMO the next step for the Beacon protocol would be to use the _handover_ object for extended responses, with then well defined form; it would be e.g. very nice to report the matched variants from range/wildcard queries using _handover_, instead of loading them directly into the response (we demonstrate this in [Beacon+](http://beacon.progenetix.org)).

**Comment by blankdots** [comment]
@mbaudis hmm, well ok. I was judging on the structure of JSON and the examples, and there seems to be a strong resemblance.
Also maybe a resemblance to JSON-LD (purely based on the structure), but that is a different discussion.

We can keep on discussing, but I've got an answer, thank you!
Issue can be closed.

**Comment by mbaudis** [comment]
You're right on all counts; but as said, not really part of the spec.; but taking this as an opportunity to maybe create even better examples - @blankdots, @sdelatorrep ... ?

I'm closing this and suggest to open a new issue w/ example of how it could look as "proper REST url", as step to possible protocol inclusion of handover endpoint (examples).
